#! /bin/bash

echo
echo "Compile the SDL2 standalone game"
echo "--------------------------------"

# Embed the fonts and drawing file in the c code as .h file.
# Compile bin_to_h.c for this (works also on Windows, contrarily to xxd)
gcc src/bin_to_h.c -o bin_to_h
./bin_to_h resources/OptimusPrinceps.ttf src/font_ttf.h
./bin_to_h resources/Chess_Pieces.svg src/pieces_svg.h
rm bin_to_h

# For gdb replace -s option (strip) by -g (gdb)
gcc src/dames.c src/engine.c -o dames -Wall -Wextra -Wimplicit-fallthrough=0 -Wpedantic `sdl2-config --libs` -lpthread -lSDL2_image -lSDL2_ttf -O3 -s

rm src/font_ttf.h
rm src/pieces_svg.h

echo

